<robot name="mycar" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="camera_length" value="0.015" />
    <xacro:property name="camera_width" value="0.025" />
    <xacro:property name="camera_height" value="0.05" />

    <!-- 摄像头 -->
    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="car_color">
                <color rgba="0 0 0 1" />
            </material>
        </visual>
    </link>

    <!-- 连接摄像头和底盘 -->
    <xacro:property name="camera_joint_x" value="${base_radius - camera_length}" />
    <xacro:property name="camera_joint_z" value="${base_length / 2 + camera_height / 2}" />

    <joint name="camera2base" type="continuous">
        <parent link="base_link" />
        <child link="camera" />
        <origin xyz="${camera_joint_x} 0 ${camera_joint_z}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>

</robot>